*start: fixed a typo

diff --git a/llstart b/llstart
--- a/llstart
+++ b/llstart
@@ -565,7 +565,7 @@ for i in "$@"; do
 done
 
 if [ -f ${rcfile/\~/$HOME} ]; then
-  source $rcfile || die "Error when sourcing $rcfile, correct it or remove it"
+  source ${rcfile/\~/$HOME} || die "Error when sourcing $rcfile, correct it or remove it"
   qecho "I have sourced $rcfile"
 fi
 
