llstart: added some extra checks (thx to mara)

diff --git a/llstart b/llstart
--- a/llstart
+++ b/llstart
@@ -13,6 +13,7 @@
 #version 0.2.2, 11.01.10 -- added --source option + cmdline in script + ibm hacks
 #version 0.2.3, 01.02.10 -- rm batchname, when crashing, resub warning
 #version 0.2.4, 25.02.10 -- added --smt option
+#version 0.3.0, 03.08.10 -- added some extra checks (thx to mara)
 
 #defaults
 usage="${0##*/} [OPTIONS] COMMAND [options]"
@@ -47,6 +48,7 @@ sleeptime=900
 scriptmode="no"
 extra_source=""
 ibm_hacks="no"
+check_runhost="no"
 
 qecho() {
   [[ "$quiet" = "no" ]] && echo "$*"
@@ -62,9 +64,14 @@ run_on_host() {
   local message ssh
   [ "$1" = "--show" ] && { shift;ssh="echo "; }
   [ -z "$1" ] && die "run_on_host: Missing argument"
-  if [ "$HOSTNAME" = "$runhost" ]; then
+  if [ "$HOSTNAME" = "$real_runhost" ]; then
     ssh="${ssh}bash -c"
   else
+    if [ "$check_runhost" = "no" ]; then
+      ssh $runhost true || die "Heuristic connection check failed.\nChange runhost variable in ${0} (now set to $runhost)
+       or make an ssh alias using sshalias (from evergreen repo) with 'sshalias -a $runhost=YOURNAME@vip.rzg.mpg.de'"
+      check_runhost="yes"
+    fi
     ssh="${ssh}ssh $runhost"
   fi
   message=$($ssh "$*" 2>&1) || die "$ssh '$*' failed\nError message: $message"
@@ -297,12 +304,16 @@ copy_back() {
   local path
   [ -z "$1" ] && die "copy_back: Missing argument"
   [ -f "$1" ] || die "$1 not found"
-  [ -z "$(grep llstart $1)" ] && die "$1 seems NOT to be a llstart script"
-  path="$(awk '/^cd/{print $2}' $1)"
-  echo Copying back data from $runhost:$path/ to .
-  scp -Cr $runhost:$path/* . || \
-    die "scp -Cr $runhost:./$path/* . failed"
-  return $?
+  if [ "${HOSTNAME}" != "$real_runhost" ]; then
+    [ -z "$(grep llstart $1)" ] && die "$1 seems NOT to be a llstart script"
+    path="$(awk '/^cd/{print $2}' $1)"
+    echo Copying back data from $runhost:$path/ to .
+    scp -Cr $runhost:$path/* . || \
+      die "scp -Cr $runhost:./$path/* . failed"
+    return $?
+  else
+    echo "You are already on $real_runhost, skipping copy back of files"
+  fi
 }
 ################################################
 ############## Main Program ####################
@@ -569,6 +580,10 @@ export LAPI_DEBUG_ENABLE_RDMA_AFFINITY=YES # also try NO
 EOF
 [[ "$myshell" = "bash" ]] && echo "[ -f ~/.bashrc ] && source ~/.bashrc" >> $batchname
 
+if [ $(run_on_host 'echo $SHELL') != "/bin/bash" ]; then
+  echo "Your shell of $runhost is NOT /bin/bash -> I will guarantee for nothing, change your shell to bash or take the risk ;-)" >&2
+fi
+
 cat <<EOF >>$batchname
 
 cd $sim_dir
@@ -615,7 +630,7 @@ if [ "${HOSTNAME}" != "$real_runhost" ]; then
      run_on_host --show "cd $sim_dir;$job_submit $batchname"
      exit 1
    fi
-   message=$(run_on_host "[ -d \$HOME/$sim_base/$batchname ] || echo Good") || die
+   message=$(run_on_host "test -d \$HOME/$sim_base/$batchname || echo Good") || die
    [ "$message" = "Good" ] || die "$runhost:\$HOME/$sim_base/$batchname exists"
    run_on_host "mkdir -p \$HOME/$sim_base/$batchname" || die "mkdir failed"
    echo Copying needed files to $runhost:./$sim_base/$batchname/
@@ -633,11 +648,9 @@ qecho "$message"
 
 if [ "$wait" = "yes" ]; then
   sleep 10
-  job_id="$(print_jobids $batchname)"
-  [[ -z "$job_id" ]] && die "Oh oh could not fetch job_id"
-  qecho "Waiting for $batchname ($job_id) to finish"
+  qecho "Waiting for $batchname to finish"
   quiet="yes"
-  while check_job $job_id; do
+  while pcheck_job $batchname; do
     sleep $sleeptime;
   done
   copy_back $batchname
