*start: add check for file after --source

diff --git a/lstart b/lstart
--- a/lstart
+++ b/lstart
@@ -803,7 +803,10 @@ ${sh_source}
 echo Hi, I am job $JOB_ID on \$HOSTNAME in \$PWD
 EOF
 
-[ -n "$extra_source" ] && echo "source $extra_source" >> $batchname
+if [ -n "$extra_source" ]; then
+  $(source $extra_source) || die "sourcing of file after --source failed, please check again"
+  echo "source $extra_source" >> $batchname
+fi
 if [ -n "${extra_begin_code}" ]; then
   cat <<EOF >>$batchname
 #BEGIN of extra begin code
diff --git a/q2start b/q2start
--- a/q2start
+++ b/q2start
@@ -936,7 +936,10 @@ cd $PWD
 echo Hi, I am job \$JOB_ID on \$HOSTNAME in \$PWD
 
 EOF
-[ -n "$extra_source" ] && echo "source $extra_source" >> $batchname
+if [ -n "$extra_source" ]; then
+  $(source $extra_source) || die "sourcing of file after --source failed, please check again"
+  echo "source $extra_source" >> $batchname
+fi
 if [ "$scratch" = "yes" ]; then
   [[ "$time" = "yes" ]] && echo date >> $batchname
   cat <<EOF >>$batchname
