*start: workaround if mktemp is missing

diff --git a/lstart b/lstart
--- a/lstart
+++ b/lstart
@@ -385,10 +385,7 @@ while [ "${1#-}" != "$1" ]; do
    shift 1 ;;
   --hostlist)
    hostlist="$2"
-   if [ ! -r "$hostlist" ]; then
-      echo hostlist not readable !
-      exit 1
-   fi
+   [ -r "$hostlist" ] || die "hostlist not readable !"
    shift 2 ;;
   --mpitype)
    mpitype="$2"
@@ -411,8 +408,7 @@ while [ "${1#-}" != "$1" ]; do
    if [ "$myshell" = "none"] || [ "$myshell" = "bash" ]; then
      :
    else
-     echo We only support bash so far \;-\)
-     exit 1
+     die "We only support bash so far ;-)"
    fi
    shift 2;;
   --batchname)
@@ -422,17 +418,13 @@ while [ "${1#-}" != "$1" ]; do
    nice="$2";
    number_check "$nice" "--priority"
    if [ $nice -lt 0 ] || [ $nice -gt 19 ]; then
-      echo argument after --nice should be a number between 0-19
-      exit 1
+      die "argument after --nice should be a number between 0-19"
    fi
    shift 2 ;;
   --lines)
    lines="$2"
    number_check "$lines" "--lines"
-   if [ $lines -lt 1 ]; then
-     echo argument after --lines should be a number greater 0
-     exit 1
-   fi
+   [ $lines -lt 1 ] && die "argument after --lines should be a number greater 0"
    shift 2 ;;
   --norun)
    run='no'
@@ -493,8 +485,7 @@ while [ "${1#-}" != "$1" ]; do
    showhelp
    exit 0;;
   *)
-   echo "Error: Unknown option '$1'"
-   exit 1;;
+   die "Error: Unknown option '$1'";;
  esac
 done
 
@@ -536,12 +527,18 @@ if [ $ncpus -eq 1 ] && [ "$findbest" = "yes" ]; then
 fi
 
 if [ -z "$batchname" ]; then
-   if [ -n $(type -p mktemp) ]; then
-      batchname=$(mktemp $name${template}) || { echo mktemp could not generate file >&2; exit 1; }
-   else
-      echo No mktemp found >&2
-      batchname=$name
-   fi
+  if [ -n $(type -p mktemp) ]; then
+    batchname=$(mktemp $name${template}) || die "mktemp could not generate file"
+  else
+    echo No mktemp found >&2
+    l=${template//[^X]}
+    l=${#l}
+    t2=${template}
+    for ((i=0;i<$l;i++)); do
+      t2=${t2/X/${RANDOM:0:1}}
+    done
+    batchname=${name}${t2}
+  fi
 fi
 
 if [ -z "$logfile" ]; then
