lstart: 95% ready

diff --git a/lstart b/lstart
--- a/lstart
+++ b/lstart
@@ -75,6 +75,8 @@ submit_host="$HOSTNAME"
 submit="yes"
 #default number of cpus to use
 ncpus=1
+#list of possible hosts
+hostlist=
 
 ########### MPI stuff ###############
 #should mpirun (or equivalent) be added: yes/no
@@ -158,6 +160,7 @@ die() {
 run_on_host() {
   local message ssh
   [ -z "$1" ] && die "run_on_host: Missing argument"
+  [ "$1" = "BEST" ] && die "Internal error BEST is a virtual hostname, please file a bug"
   if [ "$HOSTNAME" = "$submit_host" ]; then
     ssh="bash -c"
   else
@@ -176,17 +179,17 @@ To generate a setting file run:
 }
 
 check_job() {
-  local runhost pid message
+  local submit_host pid message
   [ -z "$1" ] && die "check_job: Missing argument"
   number_check "$1" "--checkjob"
   submit_host=$(show_column $1 2) || die
   pid=$(show_column $1 3) || die
   message=$(run_on_host "ps -p $pid || true") || die
   if [ -z "${message/*$pid*}" ]; then
-     qecho "Job $1: pid $pid on $runhost found"
+     qecho "Job $1: pid $pid on $submit_host found"
      return 0
   else
-    qecho "Job $1: pid $pid on $runhost NOT found"
+    qecho "Job $1: pid $pid on $submit_host NOT found"
     return 1
   fi
 }
@@ -219,7 +222,7 @@ pcheck_job() {
 }
 
 kill_job() {
-  local runhost pid gpid pids
+  local submit_host pid gpid pids
   [ -z "$1" ] && die "kill_job: Missing argument"
   number_check "$1" "--killjob"
   submit_host=$(show_column $1 2) || die
@@ -287,7 +290,22 @@ rm_job() {
 }
 
 get_next_free_jobid() {
-  die "to implement"
+  local max i
+  #if there is now jobfile we can start with one
+  [ ! -r "$jobfile" ] && echo "1" && return 0
+  max=1
+  for i in $(awk '/^[^#]/{print $1}' $jobfile); do
+    #i is not a number
+    [ -z "${i//[0-9]}" ] || continue
+    [ $i -ge $max ] || max=$(($i+1))
+  done
+  echo "$max"
+}
+
+find_best_host() {
+  [ -z "$hostlist" ] || die "find_best_host: no hostlist given, use --hostlist option" 
+  [ -f "$hostlist" ] || die "find_best_host: could not find listhost '$hostlist' (give it with --hostlist)"
+  die "not implemented, yet"
 }
 
 show_jobs() {
@@ -395,7 +413,8 @@ ADV     --source FILE    Source this file before run the progam
 ADV     --nompi          This is NOT a mpi job, so do NOT add mpirun (or equivalent)
 ADV                      to the command line (for ncpus > 1) automatically
 ADV     --runat HOST     Specify the host to run yourself
-ADV -b, --best           Run at the maschine with the lowest load
+ADV -b, --best           Run at the maschine with the lowest load (needed --hostlist)
+ADV     --hostlist       List of possible hosts to be used by --best
 
 
     JOBS OPTIONS:
@@ -576,6 +595,9 @@ while [ "${1#-}" != "$1" ]; do
    -b | --best )
    submit_host="BEST"
    shift 2;;
+  --hostlist )
+   hostlist="$2"
+   shift 2;;
    --showjobs )
    show_jobs
    exit $?;;
@@ -709,9 +731,7 @@ elif [ "$myshell" = "tcsh" ]; then
   fi
 fi
 
-queue_name="$(cpunr_to_queuename $ncpus)" || die
-
-JOB_ID=$(unique_number)
+JOB_ID=$(get_next_free_jobid) || die
 cat <<EOF >> $batchname
 #This script is generated by $USER@$HOSTNAME
 #on $(date)
@@ -722,7 +742,7 @@ exec > $logfile 2>&1
 echo "Renice job $JOB_ID and childs"
 renice $nice -p \$\$
 
-line="$job_id $runhost \$\$ $name $PWD $logfile $batchname"
+line="$job_id \$HOSTNAME \$\$ $name $PWD $logfile $batchname"
 echo \$line >> $jobfile
 
 ${sh_source}
@@ -802,6 +822,9 @@ if [ "$submit" = "no" ]; then
   exit 0
 fi
 
+if [ "$submit_host" = "best" ]; then
+  submit_host="$(find_best_host)" || die
+fi
 submit_job $batchname
 
 if [ "$wait" = "yes" ]; then
