qstart: tcsh support and --script option

diff --git a/qstart b/qstart
--- a/qstart
+++ b/qstart
@@ -27,6 +27,7 @@
 #version 0.7.3, 26.08.09 -- improved shell related stuff
 #version 0.7.4, 02.09.09 -- fixed small bug in --auto, added --runatnow
 #version 0.7.5, 14.09.09 -- add header in batch script
+#version 0.8.0, 18.09.09 -- tcsh support and --script option
 
 #defaults
 usage="${0##*/} [OPTIONS] COMMAND [options]"
@@ -58,20 +59,33 @@ resub=""
 myshell="${SHELL##*/}"
 wait="no"
 sleeptime=900
+scriptmode="no"
+set=""
+
+die() {
+  echo "$*" >&2
+  exit 1
+}
+
+clean_up() {
+  [[ -n "$batchname" ]] && \
+    [[ "$batchname" != "/dev/stdout" ]] && \
+    [[ -f "$batchname" ]] && \
+    rm $batchname
+}
+trap "clean_up" 1 2 3 6 15
 
 if [ "${SHELL##*/}" = "bash" ]  || [ "${SHELL##*/}" = "zsh" ]; then
   sh_cmd="export SGE_ROOT=/opt/SGE"
 elif [ "${SHELL##*/}" = "tcsh" ]; then
   sh_cmd="setenv SGE_ROOT=/opt/SGE"
 else
-  echo "Your shell ($SHELL) is not supported yet" >&2
-  sh_cmd=""
-  exit 1
+  die "Your shell ($SHELL) is not supported yet"
 fi
 
 check_job() {
-message=$(ssh $runhost "${sh_cmd};$qstat -u $USER")
-[[ $? -eq 0 ]] || exit 1
+message=$(ssh $runhost "${sh_cmd};$qstat -u $USER") || \
+  die "ssh $runhost '${sh_cmd};$qstat -u $USER' failed"
 if [ -z "$(echo -e "$message" | awk "(\$1==$1){print \$0}")" ]; then
   [[ "$quiet" = "yes" ]] || echo "Job '$1' on $runhost NOT found"
   exit 1
@@ -84,10 +98,21 @@ else
 fi
 }
 
+check_shell() {
+if [ "$myshell" = "none"i ] || \
+   [ "$myshell" = "bash" ] || \
+   [ "$myshell" = "tcsh" ] || \
+   [ "$myshell" = "zsh" ]; then
+  :
+else
+  die "Your shell is not supported yet"
+fi
+}
+
 pcheck_job() {
-[ -n "$1" ] || { echo No pattern given >&2; exit 1; }
-message=$(ssh $runhost "${sh_cmd};$qstat -u $USER")
-[[ $? -eq 0 ]] || exit 1
+[ -n "$1" ] || die "No pattern given"
+message=$(ssh $runhost "${sh_cmd};$qstat -u $USER") || \
+  die "ssh $runhost '${sh_cmd};$qstat -u $USER' failed"
 if [ -z "$(echo -e "$message" | awk "(\$3 ~ /${1:0:8}/){print \$0}")" ]; then
   [[ "$quiet" = "yes" ]] || echo "Job with name matching '${1:0:8}' on $runhost NOT found"
   exit 1
@@ -101,29 +126,24 @@ fi
 }
 
 kill_job() {
-ssh $runhost "${sh_cmd};$qdel $1"
-[[ $? -eq 0 ]] || exit 1
+ssh $runhost "${sh_cmd};$qdel $1" || \
+  die "ssh $runhost '${sh_cmd};$qdel $1' failed"
 }
 
 pkill_job() {
-if [ -z "$1" ]; then
-  echo Expect a pattern
-  exit 1
-fi
-message=$(ssh $runhost "${sh_cmd};$qstat -u $USER")
-[[ $? -eq 0 ]] || exit 1
+[ -n "$1" ] || die "Expect a pattern"
+message=$(ssh $runhost "${sh_cmd};$qstat -u $USER") || \
+  die "ssh $runhost '${sh_cmd};$qstat -u $USER' failed"
 for job_id in $(echo -e "$message" | awk "(\$3 ~ /${1:0:8}/){print \$1}"); do
-  echo $0 --killjob $job_id
+  $0 --killjob $job_id
 done
 }
 
 number_check(){
 number="$1"
 option="$2"
-if [ -z "$number" ] || [ -n "${number//[0-9]}" ]; then
-  echo argument after $option should be a number
-  exit 1
-fi
+[ -z "$number" ] && die "Missing number in $option"
+[ -n "${number//[0-9]}" ] && die "Argument after $option should be a number"
 }
 
 queue_info() {
@@ -134,11 +154,10 @@ elif [ $1 -eq 2 ]; then
 elif [ $1 -eq 8 ]; then
   queue="octal.q"
 else
-  echo Number of cpus unsupported >&2
-  exit 1
+  die "Number of cpus unsupported"
 fi
-ssh $runhost "${sh_cmd};$qstat -q $queue"
-[[ $? -eq 0 ]] || exit 1
+ssh $runhost "${sh_cmd};$qstat -q $queue" || \
+  die "ssh $runhost '${sh_cmd};$qstat -q $queue' failed"
 }
 
 showhelp() {
@@ -156,10 +175,12 @@ SCRIPT OPTIONS:
                      Default:  \$(mktemp ${name}$template)
                      (Argument is NAME+TEMPLATE)
 -l, --log NAME       Change name of the output file
-                     Default: log_"batchname"
+                     Default: log_"batch"
     --template TEXT  Change template for mktemp
                      Default: $template
--a, --auto           Use first argument as global name
+-a, --auto           Use first argument as name
+    --script         Will use the argument as base scripts and concatenate them
+                     (implies --nompirun)
 -e, --emptytemplate  Same as --template ""
 -m, --mail NAME      send mail to NAME
                      default: '$mail'
@@ -234,13 +255,13 @@ eoh
 }
 
 show_jobs() {
-ssh $runhost "${sh_cmd};$qstat -u $USER"
-[[ $? -eq 0 ]] || exit 1
+ssh $runhost "${sh_cmd};$qstat -u $USER" || \
+  die "ssh $runhost '${sh_cmd};$qstat -u $USER' failed"
 }
 
 show_logs() {
-message=$(ssh $runhost "${sh_cmd};$qstat -r -j $1")
-[[ $? -eq 0 ]] || exit 1
+message=$(ssh $runhost "${sh_cmd};$qstat -r -j $1") || \
+  die "ssh $runhost '${sh_cmd};$qstat -r -j $1' failed"
 path=$(echo -e "$message" | awk '/^cwd/{ print $2}')
 logfile=$(echo -e "$message" | awk '/^stdout_path_list:/{ print $2}')
 $2 $path/$logfile
@@ -284,6 +305,10 @@ while [ "${1#-}" != "$1" ]; do
    -a | --auto )
    auto="yes"
    shift ;;
+  --script )
+   scriptmode="yes"
+   mpirun="no"
+   shift ;;
    --norun )
    run="no"
    shift ;;
@@ -321,13 +346,6 @@ while [ "${1#-}" != "$1" ]; do
    shift 2 ;;
    --shell)
    myshell="$2"
-   if [ "$myshell" = "none"] || [ "$myshell" = "bash" ]; then
-     :
-   else
-     echo We only support bash so far \;-\)
-     echo "Try 'vim $0' and look for 'TCSH'"
-     exit 1
-   fi
    shift 2 ;;
    --nompirun )
    mpirun="no"
@@ -377,25 +395,16 @@ while [ "${1#-}" != "$1" ]; do
    showhelp
    exit 0;;
   *)
-   echo "Unknown option '$1'" >&2
-   exit 1;;
+   die "Unknown option '$1'"
+   exit 0;;
  esac
 done
 
-if [ -z "$1" ]; then
-  echo Missing program name
-  echo $usage
-  echo help with --help
-  exit 1
-fi
+[ -z "$1" ] && die "Missing program name (try --help)"
+check_shell
 
 [[ $auto = "yes" ]] && name=$1
 
-if [ "$mpirun" = "no" ] || [ $ncpus -eq 1 ]; then
-  cmdline="$*"
-else
-  cmdline="$mpicmd -np $ncpus $*"
-fi
 
 if [ -z "$batchname" ]; then
   if [ -n $(type -p mktemp) ]; then
@@ -421,35 +430,44 @@ fi
 
 #TCSH changes go here
 #first line, source, for loop?
-cat <<EOF >$batchname
-#! /bin/bash
+if [ "$myshell" = "bash" ] || [ "$myshell" = "none" ]; then
+  echo "#! /bin/bash" > $batchname
+elif [ "$myshell" = "zsh" ]; then
+  echo "#! /usr/bin/zsh" > $batchname
+elif [ "$myshell" = "tcsh" ]; then
+  echo "#! /bin/tcsh" > $batchname
+  set="set "
+else
+  die "Unsupported shell"
+fi
+cat <<EOF >>$batchname
 #This script is generated by $USER@$HOSTNAME
 #on $(date)
 #using $($0 --version)
+
+#sge options
 EOF
 if [ $ncpus -eq 1 ]; then
-  echo \#$ -q all.q >> $batchname
+  echo "#$ -q all.q" >> $batchname
 elif [ $ncpus -eq 2 ]; then
-  echo \#$ -q dual.q >> $batchname
-  echo \#$ -pe lammpi2cpu 2 >> $batchname
+  echo "#$ -q dual.q" >> $batchname
+  echo "#$ -pe lammpi2cpu 2" >> $batchname
 elif [ $ncpus -eq 8 ]; then
-  echo \#$ -q octal.q >> $batchname
-  echo \#$ -pe lammpi8cores 8 >> $batchname
+  echo "#$ -q octal.q" >> $batchname
+  echo "#$ -pe lammpi8cores 8" >> $batchname
 else
-  echo Number of cpus unsupported >&2
-  [[ "$batchname" = "/dev/stdout" ]] || rm $batchname
-  exit 1
+  die "Number of cpus unsupported"
 fi
 
 if [ -n "$hostname" ]; then
-  echo \#$ -l hostname=${hostname} >> $batchname
+  echo "#$ -l hostname=${hostname}" >> $batchname
 fi
   
 if [ -z "$mail" ]; then
-  echo \#$ -m n >> $batchname
+  echo "#$ -m n" >> $batchname
 else
-  echo \#$ -m e >> $batchname
-  echo \#$ -M $mail >> $batchname
+  echo "#$ -m e" >> $batchname
+  echo "#$ -M $mail" >> $batchname
 fi
 
 cat <<EOF >>$batchname
@@ -460,44 +478,56 @@ cat <<EOF >>$batchname
 EOF
 
 [[ "$myshell" = "bash" ]] && echo "source ~/.bashrc" >> $batchname
+[[ "$myshell" = "zsh" ]] && echo "source ~/.zshrc" >> $batchname
+[[ "$myshell" = "tcsh" ]] && echo "source ~/.cshrc" >> $batchname
 
 cat <<EOF >>$batchname
 
 cd $PWD
-echo I am job \$JOB_ID on \$HOSTNAME
+echo Hi, I am job \$JOB_ID on \$HOSTNAME
+
 EOF
 
 if [ "$scratch" = "yes" ]; then
   [[ "$time" = "yes" ]] && echo date >> $batchname
   cat <<EOF >>$batchname
-olddir=\$PWD
+#Copy the needed files 
+${set}olddir=\$PWD
 echo Copy needed files:
 echo $filelist
-newdir=$scratch_dir/\$USER/\$JOB_ID
-mkdir -p \$newdir
-for myfile in $filelist; do
-  cp \$myfile \$newdir
-done
+${set}newdir=$scratch_dir/\$USER/\$JOB_ID
+mkdir -p \$newdir || exit 1
+cp $filelist \$newdir
 echo finished copying files
 cd \$newdir
+
 EOF
 fi
 
 echo echo Starting simulation >> $batchname
 [[ "$time" = "yes" ]] && echo date >> $batchname
-echo "$cmdline" >> $batchname
+if [ "$scriptmode" = "yes" ]; then
+  [ -f "$1" ] || die "File '$1' not found"
+  cat "$@" >> $batchname 
+elif [ "$mpirun" = "no" ] || [ $ncpus -eq 1 ]; then
+  echo "$*" >> $batchname
+else
+  echo "$mpicmd -np $ncpus $*" >> $batchname
+fi
 echo result=\$? >> $batchname
 
 if [ "$scratch" = "yes" ]; then
   [[ "$time" = "yes" ]] && echo date >> $batchname
   cat <<EOF >>$batchname
+
+#Copy files back  
 echo Copy back files:
 echo *
 cp -u * \$olddir
 echo finished copying files
 cd \$olddir
 echo Removing scratch dir
-[[ \$result -eq 0 ]] && rm -fr \$newdir
+[ \$result -eq 0 ] && rm -fr \$newdir
 EOF
 fi
 [[ "$time" = "yes" ]] && echo date >> $batchname
@@ -506,9 +536,9 @@ if [ -n "$resub" ]; then
     echo Error: Resub and print options make no sense together >&2
     echo Error: Filename after $qsub in next line will be wrong !!! >&2
   fi
-  echo "[[ \$result -eq 0 ]] && [[ ! -f $resub ]] && { $qsub $PWD/$batchname; exit 0; }" >> $batchname
+  echo "[ \$result -eq 0 ] && [ ! -f $resub ] && { $qsub $PWD/$batchname; exit 0; }" >> $batchname
 fi
-[[ -z "$finish_file" ]] || echo "[[ \$result -eq 0 ]] && touch $finish_file" >> $batchname
+[[ -z "$finish_file" ]] || echo "[ \$result -eq 0 ] && touch $finish_file" >> $batchname
 
 if [ "$run" = "no" ]; then
   [[ "$batchname" != "/dev/stdout" ]] && echo "ssh $runhost '${sh_cmd};cd $PWD;$qsub $qsub_opts $batchname'"
