qstart: assigned test.q if walltime <= 20min

diff --git a/qstart b/qstart
--- a/qstart
+++ b/qstart
@@ -49,6 +49,7 @@
 #version 0.9.10,07.07.10 -- added connection check
 #version 1.0.0 ,13.08.10 -- major variable renaming added --rcfile option
 #version 1.0.1 ,16.08.10 -- added --nooldnodes and extra_XXX_code rc options
+#version 1.0.2 ,19.08.10 -- assigned test.q if walltime <= 20min
 
 #BEGIN DEFAULTS
 #defaults options, uncomment and change only the lines you realy need to change
@@ -279,7 +280,29 @@ cpunr_to_queuename() {
   else
     die "Do not know how to handle this Number of cpus '$nrcpus'"
   fi
-  [ "$no_old_nodes" = "yes" ] && expand_queue $queue || echo $queue
+  if [ "$no_old_nodes" = "yes" ]; then
+    expand_queue $queue
+  else
+    # test.q has max 20min and runs on an old node
+    if [ $(walltime_to_sec $wall_time) -le 1200 ] && [ $1 -eq 1 ] ; then
+      echo test.q
+    else
+      echo $queue
+    fi
+  fi
+}
+
+walltime_to_sec() {
+  local secs wall
+  [ -z "$1" ] && die "walltime_to_sec: Missing argument"
+  [ -z "${1/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]}" ] || die "Wall clock time should have the format HH:MM:SS"
+  wall="$1"
+  secs=${wall##*:}
+  wall=${wall%:??}
+  secs=$(( $secs + 60*${wall##*:} ))
+  wall=${wall%:??}
+  secs=$(( $secs + 3600*${wall##*:} ))
+  echo "$secs"
 }
 
 expand_queue(){
@@ -387,9 +410,9 @@ Notes for usage of scratch space:
 ------------------------
 -The usage of the scratch space is complicated, use it with care!
 -Only use scratch space if you expect heavy input/output load
--You may add the input files to copy to the scratch dir  with --needed 
+-You may add the input files to copy to the scratch dir  with --needed
  or use "--needed '*'", if want to copy all files of the current dir.
--If the binary in not in your PATH, give the full path of binary or 
+-If the binary in not in your PATH, give the full path of binary or
  add itself to --needed itself and use "./"
 -Remember, copying input files to the scratch dir and output file back here
  takes time, so substract time needed for that from the wall of the actual simulation!
@@ -666,6 +689,7 @@ else
 fi
 
 queue_name="$(cpunr_to_queuename $ncpus)" || die
+[ "$batchname" != "/dev/stdout" ] && [ "$queue_name" = "test.q" ] && echo "#Test queue assigned"
 
 cat <<EOF >> $batchname
 #This script is generated by $USER@$HOSTNAME
