qstart: improved help if connection fails

diff --git a/qstart b/qstart
--- a/qstart
+++ b/qstart
@@ -172,8 +172,17 @@ run_on_host() {
     ssh="bash -c"
   else
     if [ "$checked_connection" = "no" ]; then
-      ssh $submit_host true || die "Heuristic connection check failed.\nChange runhost variable in ${0} (now set to $submit_host)
-       or make an ssh alias using sshalias (from evergreen repo) with 'sshalias -a $submit_host=YOURNAME@thop100'"
+      ssh $submit_host true || die "Heuristic connection check failed.
+Change 'submit_host' variable in your setting file ($rcfile), which is now set to '$submit_host'
+or make an ssh alias by adding the following block to your ~/.ssh/config:
+####BEGIN COPY####
+Host $submit_host
+	User <YOURNAME>
+	Hostname vip.rzg.mpg.de
+####END COPY####
+
+To generate a setting file run:
+   '${0##*/} --showdefaults > $rcfile'"
       checked_connection="yes"
     fi
     ssh="ssh $submit_host"
