removed tailing spaces

diff --git a/qstart b/qstart
--- a/qstart
+++ b/qstart
@@ -34,14 +34,14 @@
 #version 0.8.4, 02.11.09 -- fixed a bug in --pcheck
 #version 0.8.5, 03.11.09 -- fixed another bug in --pcheck + pcheck help
 #version 0.8.6, 24.11.09 -- added --showdir + better output in logfile
-#version 0.8.7, 07.12.09 -- exec lamboot if no lamd is running 
-#version 0.8.8, 04.01.10 -- add -- option 
-#version 0.9.0, 06.01.10 -- fixed a bug in emptyfile list (thx to sasha) 
+#version 0.8.7, 07.12.09 -- exec lamboot if no lamd is running
+#version 0.8.8, 04.01.10 -- add -- option
+#version 0.9.0, 06.01.10 -- fixed a bug in emptyfile list (thx to sasha)
 #version 0.9.1, 07.01.10 -- clean up, added run_on_host
 #version 0.9.2, 11.01.10 -- added --source option + cmdline in script
 #version 0.9.3, 01.02.10 -- rm batchname, when crashing, resub warning
 #version 0.9.4, 04.02.10 -- added some checks for .*shrc files + removed sh_cmd
-#version 0.9.5, 10.02.10 -- make resub work in tcsh (thx to christine) 
+#version 0.9.5, 10.02.10 -- make resub work in tcsh (thx to christine)
 
 #defaults
 usage="${0##*/} [OPTIONS] COMMAND [options]"
@@ -121,8 +121,8 @@ pcheck_job() {
   local job_id myjobs failed
   [ -n "$1" ] || die "pcheck_job: No pattern given"
   myjobs="$(print_jobids $1)" || die
-  if [ -z "$myjobs" ]; then 
-    qecho "No jobs matching $1 found" 
+  if [ -z "$myjobs" ]; then
+    qecho "No jobs matching $1 found"
     return 1
   fi
   failed="yes"
@@ -181,7 +181,7 @@ queue_info() {
     die "Number of cpus unsupported"
   fi
   run_on_host "$qstat -q $queue"
-  return $? 
+  return $?
 }
 
 showhelp() {
@@ -218,7 +218,7 @@ SCRIPT OPTIONS:
                      Exit status from existence of FILE from --finish or --resub
     --sleeptime      Changes the sleeptime for --wait
                      Default: $sleeptime
-    --shell NAME     Change the shell to use, script will sources ~/.XXXrc   
+    --shell NAME     Change the shell to use, script will sources ~/.XXXrc
                      Default: $myshell
     --source FILE    Source this file before run the progam
     --scratch        Use scratch on "$scratch_dir/\$USER/"
@@ -259,7 +259,7 @@ COMMON OPTIONS:
 Notes for scratch space :
 ------------------------
 -The usage of the scratch space is still at the beginning of testing,
- use it with care! 
+ use it with care!
 -You may add the files to copy there with --needed or use "--needed '*'",
  if your job has a separate dir.
 -Give the full path of binary or add itself to --needed and use "./", if
@@ -273,7 +273,7 @@ Examples:
    ${0##*/} -8 --needed topol.tpr mdrun
    ${0##*/} "echo -e \"SOL\nSOL\" | g_rdf -b 100 -n index.ndx"
    ${0##*/} -8 --resub confout.gro  mdrun -append -cpi state.cpt -maxh 36
-            (Note: -cpi is smart, the first time mdrun will start normal!)         
+            (Note: -cpi is smart, the first time mdrun will start normal!)
    ${0##*/} -8 --needed '*' --resub confout.gro  mdrun -append -cpi state.cpt -maxh 35
             (Note: --needed '*' needs a separate dir for the simulation!)
 
@@ -459,7 +459,7 @@ done
 
 if [ -z "$batchname" ]; then
   if [ -n $(type -p mktemp) ]; then
-    batchname=$(mktemp ${name}${template}) || die "mktemp could not generate file" 
+    batchname=$(mktemp ${name}${template}) || die "mktemp could not generate file"
   else
     echo No mktemp found >&2
     batchname=$name
@@ -514,7 +514,7 @@ fi
 if [ -n "$hostname" ]; then
   echo "#$ -l hostname=${hostname}" >> $batchname
 fi
-  
+
 if [ -z "$mail" ]; then
   echo "#$ -m n" >> $batchname
 else
@@ -551,7 +551,7 @@ EOF
 if [ "$scratch" = "yes" ]; then
   [[ "$time" = "yes" ]] && echo date >> $batchname
   cat <<EOF >>$batchname
-#Copy the needed files 
+#Copy the needed files
 ${set}olddir=\$PWD
 ${set}newdir=$scratch_dir/\$USER/\$JOB_ID
 mkdir -p \$newdir || exit 1
@@ -571,7 +571,7 @@ echo echo Starting simulation >> $batchname
 if [ "$scriptmode" = "yes" ]; then
   for i in $@; do
     [ -f "$i" ] || die "File '$i' not found"
-    cat "$i" >> $batchname 
+    cat "$i" >> $batchname
   done
 elif [ "$mpirun" = "no" ] || [ $ncpus -eq 1 ]; then
   echo "$*" >> $batchname
@@ -587,7 +587,7 @@ if [ "$scratch" = "yes" ]; then
   [[ "$time" = "yes" ]] && echo date >> $batchname
   cat <<EOF >>$batchname
 
-#Copy files back  
+#Copy files back
 echo Copy back files:
 echo *
 cp -ru * \$olddir
@@ -619,7 +619,7 @@ message="$(run_on_host "cd $PWD;$qsub $qsub_opts $batchname")" || die
 qecho "$message"
 
 if [ "$wait" = "yes" ]; then
-  job_id="$(echo "${message}" | sed -n 's/^Your job \([0-9]*\) (".*$/\1/p')" 
+  job_id="$(echo "${message}" | sed -n 's/^Your job \([0-9]*\) (".*$/\1/p')"
   [[ -z "$job_id" ]] && die "Oh oh could not fetch job_id"
   qecho "Waiting for $batchname ($job_id) to finish"
   quiet="yes"
