qstart: merge with llstart

diff --git a/qstart b/qstart
--- a/qstart
+++ b/qstart
@@ -69,7 +69,10 @@ job_info="$queue_path/qconf"
 #extra options for submit
 submit_opts=""
 #name of the host, where to submit the jobs
+#maybe create an sshalias
 submit_host="thop100"
+#the real hostname ($HOSTNAME), when logon submit_host
+real_submit_hostname="$submit_host"
 #submit the script by default: yes/no
 submit="yes"
 #default number of cpus to use
@@ -160,18 +163,18 @@ die() {
 run_on_host() {
   local message ssh
   [ -z "$1" ] && die "run_on_host: Missing argument"
-  if [ "$HOSTNAME" = "$submit_host" ]; then
+  if [ "$HOSTNAME" = "$real_submit_hostname" ]; then
     ssh="bash -c"
   else
     if [ "$checked_connection" = "no" ]; then
       ssh $submit_host true || die "Heuristic connection check failed.\nChange runhost variable in ${0} (now set to $submit_host)
-       or make an ssh alias using sshalias (from evergreen repo) with 'sshalias -a $sbumit_host=YOURNAME@vip.rzg.mpg.de'"
+       or make an ssh alias using sshalias (from evergreen repo) with 'sshalias -a $submit_host=YOURNAME@thop100'"
       checked_connection="yes"
     fi
     ssh="ssh $submit_host"
   fi
   message=$($ssh "$*" 2>&1) || die "$ssh '$*' failed\nError message: $message"
-  echo -e "$message"
+  [ -z "$message" ] || echo -e "$message"
 }
 
 check_job() {
@@ -219,10 +222,11 @@ stat_job() {
 }
 
 submit_job() {
-  local message
+  local message path
   [ -z "$1" ] && die "submit_job: missing argument"
   [ -f "$1" ] || die "Could not find $1"
-  message="$(run_on_host $show "cd $PWD;$job_submit $submit_opts $batchname")" || die
+  path="$(get_path_from_script $1)" || die
+  message="$(run_on_host "cd $path;$job_submit $submit_opts $batchname")" || die
   qecho "$message"
 }
 
@@ -290,7 +294,7 @@ expand_queue(){
 queue_info() {
   local queue
   number_check "$1" "--queueinfo"
-  queue=$(cpunr_to_queuename "$1") || die
+  queue="$(cpunr_to_queuename "$1")" || die
   run_on_host "$job_info -sq $queue"
   return $?
 }
@@ -426,6 +430,16 @@ show_path() {
   return $?
 }
 
+get_path_from_script(){
+  local path
+  [ -z "$1" ] && die "get_path_from_script: Missing argument"
+  [ -f "$1" ] || die "get_path_from_script: Could not found"
+  [ -z "$(grep -e '${0##*/}' $1)" ] && die "$1 seems NOT to be a '${0##*/}' script"
+  path="$(awk '/^cd/{print $2;exit 0}' $1)"
+  [ -z "$path" ] && die "get_path_from_script: found not grep path from $1"
+  echo "$path"
+}
+
 ################################################
 ############## Main Program ####################
 ################################################
@@ -460,6 +474,7 @@ while [ "${1#-}" != "$1" ]; do
    exit 0;;
   -[0-9] )
    ncpus=${1#-}
+   number_check "$ncpus" "$1"
    shift;;
   -p | --print )
    batchname="/dev/stdout"
@@ -596,8 +611,7 @@ while [ "${1#-}" != "$1" ]; do
    shift
    break;;
   *)
-   die "Unknown option '$1'"
-   exit 1;;
+   die "Unknown option '$1'";;
  esac
 done
 
@@ -647,9 +661,9 @@ else
   die "Unsupported shell"
 fi
 
-queue_name=$(cpunr_to_queuename $ncpus) || die
+queue_name="$(cpunr_to_queuename $ncpus)" || die
 
-cat <<EOF >>$batchname
+cat <<EOF >> $batchname
 #This script is generated by $USER@$HOSTNAME
 #on $(date)
 #by the command "$cmdline"
@@ -663,6 +677,18 @@ cat <<EOF >>$batchname
 #$ -q ${queue_name}
 $(extra_queue_header $ncpus)
 EOF
+
+if [ -n "$hostname" ]; then
+  echo "#$ -l hostname=${hostname}" >> $batchname
+fi
+
+#To mail or not to mail
+if [ -z "$mail" ]; then
+  echo "#$ -m n" >> $batchname
+else
+  echo "#$ -m e" >> $batchname
+  echo "#$ -M $mail" >> $batchname
+fi
 
 if [ "$myshell" = "bash" ]; then
   echo "#$ -S /bin/bash" >> $batchname
@@ -679,17 +705,6 @@ elif [ "$myshell" = "tcsh" ]; then
   fi
 elif [ "$myshell" = "none" ]; then
   echo "#$ -S /bin/bash" >> $batchname
-fi
-
-if [ -n "$hostname" ]; then
-  echo "#$ -l hostname=${hostname}" >> $batchname
-fi
-
-if [ -z "$mail" ]; then
-  echo "#$ -m n" >> $batchname
-else
-  echo "#$ -m e" >> $batchname
-  echo "#$ -M $mail" >> $batchname
 fi
 
 cat <<EOF >>$batchname
@@ -727,6 +742,7 @@ EOF
 fi
 
 echo echo Starting simulation >> $batchname
+
 [[ "$time" = "yes" ]] && echo date >> $batchname
 [[ $ncpus -ne 1 ]] && echo "pgrep lamd > /dev/null || $lamboot_cmd" >> $batchname
 if [ "$scriptmode" = "yes" ]; then
@@ -735,11 +751,13 @@ if [ "$scriptmode" = "yes" ]; then
     cat "$i" >> $batchname
   done
 elif [ "$mpi_job" = "no" ] || [ $ncpus -eq 1 ]; then
-  echo "$*" >> $batchname
+  cmdline="$*"
 else
-  echo "$mpirun_cmd -np $ncpus $*" >> $batchname
+  cmdline="$mpirun_cmd -np $ncpus $*"
 fi
+
 cat <<EOF >>$batchname
+$cmdline
 ${set}result=\$?
 [ \$result -ne 0 ] && echo "\$JOB_ID finished unhappy!"
 EOF
@@ -766,17 +784,19 @@ echo Removing scratch dir
 [ \$result -eq 0 ] && rm -fr \$newdir
 EOF
 fi
+
 [[ "$time" = "yes" ]] && echo date >> $batchname
+
 if [ -n "$resubmit_file" ]; then
   [ -f "$resubmit_file" ] && die "Resub is already there, unlogical !"
   if [ "$batchname" = "/dev/stdout" ]; then
     echo Error: Resub and print options make no sense together >&2
     echo Error: Filename after $job_submit in next line will be wrong !!! >&2
   fi
-  echo "[ \$result -eq 0 ] && [ ! -f "$resubmit_file" ] && $job_submit $PWD/$batchname" >> $batchname
+  echo "[ \$result -eq 0 ] && [ ! -f '$resubmit_file' ] && $job_submit $PWD/$batchname" >> $batchname
   [ -z "$finish_file" ] || echo "[ \$result -eq 0 ] && [ -f $resubmit_file ] && touch $finish_file" >> $batchname
 else
-  [ -z "$finish_file" ] || echo "[ \$result -eq 0 ] && touch $finish_file" >> $batchname
+  [ -z "$finish_file" ] || echo "[ \$result -eq 0 ] && touch '$finish_file'" >> $batchname
 fi
 
 if [ "$submit" = "no" ]; then
